#define ${CONFIG_PROJECT_NAME}_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define ${CONFIG_PROJECT_NAME}_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define ${CONFIG_PROJECT_NAME}_VERSION_PATCH ${PROJECT_VERSION_PATCH}
#define ${CONFIG_PROJECT_NAME}_VERSION "${PROJECT_VERSION}"

#cmakedefine ENABLE_TESTS
#cmakedefine ENABLE_DEBUG
